### PR TITLE
Added peek command

### PR DESCRIPTION
**Pull request by pkruithof**

### CODE REVIEW

**Comment by cleentfaar** [comment]
Missing something like 

> This command lets users see which job is next in the queue, optionally filtered by the action and/or state.

Can you also give an example of when/why you would use this?

**Comment by pkruithof** [comment]
It has both a [description and help](https://github.com/treehouselabs/worker-bundle/pull/6/files#diff-ee91ccc01548295da43dd7b1a65b110eR40), what are you missing?

See #5 for a use case.

**Comment by cleentfaar** [comment]
tip (probably not for this PR);

To display some object or mapping in a consistent way in console output, you can create a `Descriptor` class (implementing `DescriptorInterface`) that does it for you; just makes it easier to test and separates concerns a bit, and looks cool too :smile: : `$descriptor->describe($io, $actions, [])`, see: https://github.com/symfony/framework-bundle/blob/master/Command/RouterDebugCommand.php#L103-L108

**Comment by cleentfaar** [comment]
lgtm

**Comment by mvanduijker** [comment]
lgtm

**Pull request merged**
